server:
  port: 8761     #指定服务端口

eureka:
  client:
#    defaultZone: http://localhost:8761/eureka/
    defaultZone: http://172.16.73.128:8761/eureka/
    registerWithEureka: false  #是否将eureka自身作为应用注册到eureka注册中心
    fetchRegistry: false       #为true时，可以启动，但报异常：Cannot execute request on any known server


  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

#  instance:
#    statusPageUrlPath: ${management.contextPath}/info
#    healthCheckUrlPath: ${management.contextPath}/health