server:
  port: 8081

spring:
  application:
    name: client01    #为你的应用起个名字，该名字将注册到eureka注册中心


eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.73.128:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/