server:
  port: 7071


spring:
  application:
    name: sayhello-server    #为你的应用起个名字，该名字将注册到eureka注册中心


eureka:
  server:
      enableSelfPreservation: false
  client:
    serviceUrl:
      defaultZone: http://172.16.73.128:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/